### ISSUE TITLE
One code to many buttons without sliders arrows

### ISSUE THREAD

**Issue by Alexufo** [biati-digital/glightbox#94] opened 2020-02-28 01:52 UTC
I use one code  and several buttons to call one popup but then I click on some element I see sliders arrows. How i can disable sliders arrows? 
````
let tel = GLightbox({
    selector: 'js-call'
});
````

**Comment by biati-digital** [comment] 2020-05-09 18:30
Closed as duplicate of your other issue #98

**Closed by biati-digital** 2020-05-09 18:30 UTC
