### ISSUE TITLE
e.getAttribute is not a function

### ISSUE THREAD

**Issue by schmidfelix** [biati-digital/glightbox#147] opened 2020-08-12 21:07 UTC
**Describe the bug**
I have installed the package via CDN and when I load the page I get following error:
`glightbox.min.js:1 Uncaught TypeError: e.getAttribute is not a function
    at e.value (glightbox.min.js:1)
    at e.value (glightbox.min.js:1)
    at Array.<anonymous> (glightbox.min.js:1)
    at a (glightbox.min.js:1)
    at e.value (glightbox.min.js:1)
    at e.value (glightbox.min.js:1)
    at glightbox.min.js:1
    at (index):263`

I have seen #132 and I think that would be the solution for my problem? I dont init the lightbox via an element, only with javascript.

Should I modify the JS and add the code from the PR or how can I solve this?

**Are you able to reproduce the bug in the demo site**
Yes.

**Post the code you are using**
`
const videoGallery = GLightbox({
        elements: [],
        descPosition: 'top',
        autoplayVideos: true,
        plyr: {
            css: 'https://cdn.plyr.io/3.6.2/plyr.css',
            js: 'https://cdn.plyr.io/3.6.2/plyr.js',
            ratio: '16:9',
            config: {
                controls: ['play-large', 'play', 'progress', 'current-time', 'mute', 'volume', 'airplay', 'fullscreen'],
                iconUrl: '../../../../assets/video-icons/mfa-video-icons.svg',
                iconPrefix: 'mfa',
            }
        }
    })

    $(this).ready(function () {
        $('.__open_video').on('click', function () {
            let title = $(this).data('title');
            let subtitle = $(this).data('subtitle');
            let source = $(this).data('url');
            var elements = [{
                href: source,
                type: 'video',
                source: 'local',
                title: title,
                description: subtitle
            }]
            videoGallery.setElements(elements)
            videoGallery.open()
        })
    })
`

**Desktop:**

**Smartphone:**

**Comment by biati-digital** [comment] 2020-08-13 02:36
Thanks for the info. Actually this is different from the issue #132 that issue was fixed but in the latest update GLightbox was rewritten to separate the code in different files and folders and a similar error was introduced in the slides parser, with the info you posted and example i'll be able to fix this but probably wont be able to do it until this weekend.

If you want to send a PR, the problem is in src/core/slide-parser.js in the method "parseConfig"

**Comment by schmidfelix** [comment] 2020-08-13 07:23
I have created a PR #148

**Comment by biati-digital** [comment] 2020-08-17 04:34
Thank's for the PR, i ended up adjusting the code in another part as i didn't want to call the **parseConfig** method on an empty elements list.

Anyway, this is fixed in the latest version 3.0.4 and thank's again for the PR.

**Closed** 2020-09-13 21:02 UTC
