### ISSUE TITLE
Call to "destroy" results in error

### ISSUE THREAD

**Issue by sayontan** [biati-digital/glightbox#180] opened 2020-11-28 23:14 UTC
Hello, and sorry for my third bug report in 24 hours.

I have observed that if I try to call the `destroy` function, I get an error saying:

```
Uncaught ReferenceError: evt is not defined
    at GlightboxInit.clearAllEvents (glightbox.js:3385)
```

In looking through the code, it looks like this is causing the issue:

```
      key: "clearAllEvents",
      value: function clearAllEvents() {
        this.apiEvents.push({
          evt: evt,
          once: once,
          callback: callback
        });
```
I believe if you change it to something like this you will be fine:
```
        var self = this;
        this.apiEvents.push({
          evt: self.evt,
          once: self.once,
          callback: self.callback
        });
```

**Comment by biati-digital** [comment] 2020-11-29 06:57
Hi, before creating an issue please try to search if that same issue already exists. This is a duplicate of #175 and your issue is #180. There's already a pull requests to fix this issue.

**Closed by biati-digital** 2020-11-29 06:57 UTC
