### ISSUE TITLE
Video always has maxWidth 900px because of hardcoded setting

### ISSUE THREAD

**Issue by TheOnlySpeedy** [biati-digital/glightbox#203] opened 2021-02-03 22:32 UTC
https://github.com/biati-digital/glightbox/blob/2ecad08e42c727559b82a618fcd2694697cc8f84/src/js/glightbox.js#L1080-L1082

I stumbled upon this library and must say: i really like it

but sadly, because of the hardcoded value above, videos are always a maximum of 900 pixels
is there any specific reason why it's done that way and not with `let maxWidth = slideData.width;` ?

**Comment by biati-digital** [comment] 2021-02-05 18:10
This is something I need to take a look, the problem is that I need to know the width and ratio to calculate the max height so it's resized correctly horizontally when the viewport width is smaller than the viewport height and resize vertically when the viewport height is smaller than the width, I need to update that part of the code to work with values like 90vw or 90% or update the CSS, not sure, I'll have to make some tests.

There's also another issue #196 that it's related to this topic. I'll take a look at this when I have some free time.

**Comment by biati-digital** [comment] 2021-04-10 03:26
This is fixed in 3.0.8, now you can specify any value you want for the videos width, for example: `1200px` or `100%` or even `95vw`

**Comment by TheOnlySpeedy** [comment] 2021-04-12 06:54
Awesome! :+1: 
Going to test it later this week! :grin:

**Closed** 2021-05-20 04:34 UTC
