### ISSUE TITLE
You can zoom next slide image if current slide is not full height

### ISSUE THREAD

**Issue by ncla** [biati-digital/glightbox#261] opened 2021-06-22 10:20 UTC
**Describe the bug**
Title.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/
2. Open 2nd image (the apple one) in "Simple Image Gallery" section
3. If you hover above the current slide image, you will see zoom-in cursor (assuming you have enough vertical space, but 1080p screen should suffice)
4. Clicking the area above current slide image will zoom next slide (you can verify this by looking at DOM changes)
5. Navigate to the next slide and you will find that image is indeed zoomed in

![image](https://user-images.githubusercontent.com/5507083/122907557-f3c21680-d35b-11eb-92b0-4f43d1aaaa59.png)

**Expected behavior**
There should be no zooming for next slide at all.

**Post the code you are using**
Bug is reproducible on your demo site.

**Screenshots**
None.

**Desktop:**
 - Brave, Ubuntu 18

**Comment by frankie-tech** [comment] 2021-06-23 18:35
Hey there @ncla,

Thanks for submitting this issue! I can confirm that the bug is happening on the website in FireFox as well.

I'll add the bug label in the meantime, but after doing a little bit of fiddling, it looks like the below CSS will work as a patch.

```css
.gslide:not(.current) {
	pointer-events: none;
}
```

**Comment by biati-digital** [comment] 2021-08-28 07:03
This is fixed in the latest version 3.1.0

**Closed by biati-digital** 2021-08-28 07:03 UTC
Labels: bug
