### ISSUE TITLE
On open/close of glightbox, other inline vimeo embeds will pause intermittently in different browsers

### ISSUE THREAD

**Issue by joepagan** [biati-digital/glightbox#306] opened 2021-12-20 18:16 UTC
Thanks for your work on this

**Describe the bug**

It appears that on my app this occurs 100% of the time, though in my code sandbox example it is intermittent for me.

The bug appears more reliably in: 

- safari
- chrome (sometimes glightbox will replace the entire body here, not sure why though refreshing a few times resolves that? 🤷 )

I have noticed that the bug is less likely to occur in: 

- chrome incognito mode
- firefox

I had seen once in chrome incognito mod ONE of the inline iframes be paused on exiting the lightbox for a few seconds which will then resume shortly after
Another bit of info worth mentioning is if an image is in the lightbox gallery and is clicked, when you exit from the lightbox the videos are continuing to play.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://codesandbox.io/s/serene-bardeen-i5y1o
2. Click one iframe which will load an lightbox with the same video
3. Close the lightbox
4. Both inline videos will be paused

**Expected behavior**
inline vimeo embeds resume playing on close

**Post the code you are using**
https://codesandbox.io/s/serene-bardeen-i5y1o

**Desktop:**
```
System:
    OS: macOS 12.0.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 89.00 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.2
    Safari: 15.1
Build system:
  Docker node 6 container
  gulp 
  vendors/node_module dependencies are referenced individually in the markup, 
  my custom code, is bundled to a generic app.js file
```

I hope you can replicate, or have some ideas on what this could be, let me know if you need anything else from me

**Comment by frankie-tech** [comment] 2022-02-11 14:02
Hey there @joepagan,

I was able to recreate the bug you were referencing on Firefox, but like you said it was less often. I will try again once I'm able to use Safari/Chrome.

Because this has to do at least in some part with the video player library that we use, plyr.js, I'm tempted to see if they have had any similar issues. There would need to be more research into why exactly the bug is happening on some browsers and not others though.

**Comment by martinbuezas** [comment] 2022-07-07 21:13
The issue is not related to Glightbox or Plyr. It is probably related to Vimeo.

I had the same scenario and was able to isolate the issue in the following way:
- Completely remove Glightbox (and Plyr)
- Have inline Vimeo embeds playing
  `<iframe src="https://player.vimeo.com/video/VIDEO_ID?background=1&autoplay=1&loop=1"></iframe>`
- Have a regular Vimeo embed
    `<iframe src="https://player.vimeo.com/video/VIDEO_ID"></iframe>`
- Play the regular video
- Inline videos stop

I solved it by using the Vimeo iframe API to resume videos when Glighbox closes
`https://player.vimeo.com/api/player.js`

```js
// ...

this.lightbox.on('close', () => {
  const inlineVideoFrames = document.querySelectorAll('iframe.vimeo-inline')

  inlineVideoFrames.forEach(iframe => {
    if (!iframe.player) {
      iframe.player = new Vimeo.Player(iframe)
    }
    iframe.player.play()
  })
})
```

**Comment by biati-digital** [comment] 2022-07-20 01:42
Yes, this is not related to GLightbox, I'll close this issue now and hope the solution posted by @martinbuezas helps other users having that problem.

**Closed** 2022-07-20 01:42 UTC
