### ISSUE TITLE
Media Buttons Not responding on Android

### ISSUE THREAD

**Issue by hugopm26** [biati-digital/glightbox#233] opened 2021-05-03 22:31 UTC
The media buttons for self-hosted video playback are not working on my two Android devices. 

**Are you able to reproduce the bug in the demo site**
Yes

The media buttons for self-hosted video playback don't respond when accessing through Google Chrome on my Galaxy S20 and my Galaxy Note 20, I get the same issue when playing videos on my website and on the live demo.

**Comment by frankie-tech** [comment] 2021-05-12 16:39
If you're refering to these buttons, those are generated by another library called [plyr.js](https://plyr.io/).

![image](https://user-images.githubusercontent.com/26461046/118011164-b52d4b00-b31d-11eb-8a76-7e4634a761f2.png)

We don't alter any of the plyr scripts or styles. I would try some of the demos they have made and see if you run into the same issue. I don't have any devices to debug this problem, but I'll add a bug tag for now.

**Comment by hugopm26** [comment] 2021-05-13 12:53
It's giving me this issue only on android devices (so far 3 different Samsung phones). The buttons work perfectly on the plyr demos, it only seems to not work when embedded on the glightbox view. When I tap on the button it only recognizes the scroll feature to move between items in the gallery, not the actual plyr buttons. It's definitely a bug in the implementation of the plyr library on glightbox.

**Comment by frankie-tech** [comment] 2021-05-16 13:16
Hmmm, that is strange. I just looked through the recent plyrjs releases and it looks like there have been a couple.

Granted, GLightbox is using `3.6.3`, so not a major jump. If you can try adding their most recent CDN link to the plyr config.

`https://cdn.plyr.io/3.6.8/plyr.js`

Here's an example:

```js
const lightbox = GLightbox({
  plyr: {
    js: "https://cdn.plyr.io/3.6.8/plyr.js",
  },
});
```

**Comment by hugopm26** [comment] 2021-05-16 20:59
I updated the plyr.js & plyr.css versions to 3.6.8 but the same issue persists.

**Comment by frankie-tech** [comment] 2021-05-17 01:03
Yeah, it was a long shot. I am unfortunately not able to find this bug on any of the phone or device simulators I have access to.

It sounds like it is possible to use chrome to do some remote debugging, https://developer.chrome.com/docs/devtools/remote-debugging/.

For now, I'll leave this open with the help wanted tag.

**Comment by hugopm26** [comment] 2021-05-17 14:11
Yeah, it only seems to have the bug on the phone itself. I'll try that for now, if I come up with a solution I'll make sure to share it here.

**Comment by denunv** [comment] 2021-05-17 15:02
I can reproduce the issue even in Chrome DevTools Device Mode. 
Looks like the touch event listener for glightbox is blocking the touch events for plyr.

**Comment by frankie-tech** [comment] 2021-05-17 22:29
Odd, I just tried it with Device Mode the demo site with the Device Mode and wasn't able to reproduce it. @denunv are you on a Mac or Windows?

**Comment by denunv** [comment] 2021-05-18 06:08
Sorry, for me it is not working with an embedded YouTube video. I am using macOS with Chrome 90.

**Comment by denunv** [comment] 2021-05-18 07:54
Autoplay, jumping in the timeline and volume control are working for me, but I cannot use the other player controls via touch (pause/play, settings, fullscreen).

**Comment by biati-digital** [comment] 2021-05-20 10:05
I've updated the demo site, can someone please try the video with an Android device?

**Comment by biati-digital** [comment] 2021-05-21 23:59
Hi @denunv or @hugopm26  i submitted some changes, can you please let me know if the error was fixed in the demo site? i do not own an Android device so not able to check this.

I've limited time as i'm about to start a new project for a client and if this is not fixed then probably i won't be able to take a look at this for some time, i need to release an update today or tomorrow.

**Comment by hugopm26** [comment] 2021-05-22 21:40
Hi @biati-digital,

The controls are working fine on android now. However on portrait video, when I click fullscreen the video doesn't take the fullscreen.

![Screenshot](https://user-images.githubusercontent.com/18062144/119241502-01457000-bb14-11eb-9bd3-15353722f3f9.jpeg)

**Comment by biati-digital** [comment] 2021-05-22 22:21
Hi @hugopm26 thank's for letting me know. About the video size, that's a different issue, please create a new issue with a code example, i need to submit an update today so probably i won't be able to check it until i finish my current project.

**Comment by biati-digital** [comment] 2021-05-25 21:35
This should be fixed in the latest version

**Closed by biati-digital** 2021-05-25 21:35 UTC
Labels: bug, help wanted
