### ISSUE TITLE
Links which open lightboxes do not open when in a lightbox

### ISSUE THREAD

**Issue by ninetyninew** [biati-digital/glightbox#316] opened 2022-02-07 15:37 UTC
If you have multiple lightboxes containing HTML content and you try to add a link within one that should open another lightbox the link does nothing - I expected this to close the current lightbox and open the linked lightbox.

**Comment by frankie-tech** [comment] 2022-02-08 13:18
Hey there @ninetyninew,

1. Please use the provided templates when creating an issue.

2. This is an anti-pattern in terms of both UX and accessibility, so is not something that is planned to be supported out of the box. Nesting interactive elements gets hairy very quickly. _You might be able to hand roll a solution, but this isn't recommended for the reasons above._

3. This is the expected behavior. GLightbox doesn't try to manage multiple lightboxes, and and instead only creates one.

Closing issue due to missing template and outside of support matrix.

**Closed** 2022-02-08 13:18 UTC
