### ISSUE TITLE
Can´t change video player width with parameter.

### ISSUE THREAD

**Issue by zzseba78** [biati-digital/glightbox#208] opened 2021-02-28 13:43 UTC
**Describe the bug**
Video player doesn´t change size using 'videosWidth' parameter.

**To Reproduce**
https://codepen.io/zzseba78/pen/NWbYvVx

**Expected behavior**
Video player should be 1200px in the example
https://codepen.io/zzseba78/pen/NWbYvVx

**Comment by frankie-tech** [comment] 2021-03-01 04:16
Currently there is a set max width of 900px to calculate aspect ratios, see #203.

I'm not able to check your CodePen, but are you able to change the width to something less than 900px?

**Comment by billmn** [comment] 2021-03-01 16:29
Yeah, same here. 

@frankie-tech I have tried with something smaller like 400px, it reduce the video width instead of the player width.

![Schermata 2021-03-01 alle 17 27 43](https://user-images.githubusercontent.com/779534/109527166-a6bbeb00-7ab3-11eb-920c-491ff306289a.png)

**Comment by zzseba78** [comment] 2021-03-01 17:06
The maxWidth is hardcoded, the creator of this lightbox is aware of this issue. It´s a shame, because this seems like a great lightbox, with gestures and smooth, but not so good for media right now.

**Comment by frankie-tech** [comment] 2021-03-01 17:53
@billmn can you post your code and the browser/OS/devices that this is happening on?

@zzseba78 I forked your pen and noticed you're defining the width on the element and in the config. If you define the width on the element using `data-width` it will override the config. But if you define both in the config, it will prefer `videosWidth` over `width` for videos.

**Comment by zzseba78** [comment] 2021-03-01 17:55
@frankie-tech Yes, i add it later, i removed it now, doesn´t work either.

**Comment by billmn** [comment] 2021-03-01 18:19
@frankie-tech I'm using Chrome on a Mac Mini.

The problem seems occur with local videos: https://codepen.io/billmn/pen/GRNdomB

**Comment by frankie-tech** [comment] 2021-03-01 18:24
@zzseba78 Yeah, unfortunately there is nothing to do right now about overriding the set 900px limit. It was a bug that I had caused for myself previously. As for a *workaround* for the time being for your max-width issue, this might help you: https://codepen.io/frankie_tech/pen/LYbmVWX?editors=1000 You can load the `iframe` using the inline content method that GLightbox offers and use CSS to manipulate the size.

You can still use [Plyr.js](https://github.com/sampotts/plyr) as well, but you would have to add and configure it manually.

**Comment by zzseba78** [comment] 2021-03-01 18:24
@billmn Local video gets small, but player doesn´t.
Youtube video is the same, doesn´t take the specified size.

![Captura de Pantalla 2021-03-01 a la(s) 15 23 06](https://user-images.githubusercontent.com/5558563/109541022-09a48680-7aa2-11eb-8405-13ba800e9095.png)

**Comment by frankie-tech** [comment] 2021-03-01 18:58
I can confirm the issue @billmn has reported is happening on Firefox and Safari on macOS 11 MacBook Pro.

The issue with the player wrapper not shrinking to fit the video is related to the fixed 900px number. You can probably also get away with the inline-content work around I [provided](codepen.io/frankie_tech/pen/LYbmVWX). I can't guarantee how much mileage you'll get out of it, though.

**Comment by frankie-tech** [comment] 2021-03-23 15:42
Since this is a duplicate of #203 I'm gonna close it unless something unique changes 😊

Thank you for filing a bug report

**Closed by frankie-tech** 2021-03-23 15:42 UTC
