### ISSUE TITLE
Zoomed image is not scrollable on desktop

### ISSUE THREAD

**Issue by paxter** [biati-digital/glightbox#135] opened 2020-07-04 16:30 UTC
**Describe the bug**
As the title states. Not testet on mobile.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/
2. Click on first image
3. Second click to zoom
4. Try scrolling (won't work)

**Expected behavior**
Scrolling should be work or it's impossible to view all content of the full image

**Post the code you are using**
Demo site should be enough

Could be related to #61

**Comment by biati-digital** [comment] 2020-07-04 16:52
That’s not a bug, the functionality is zoom and drag, you need to zoom and then drag the image to the parts you want to see (like the way you do in mobile with your finger)

**Comment by paxter** [comment] 2020-07-04 16:55
Hm ok. But that's not really intuitive for desktop systems. The first thing everybody tries to view a hidden area at the top or below is to try scrolling and not drag & drop the site content. This makes sense on mobile devices, but not on desktop.

**Comment by biati-digital** [comment] 2020-07-04 16:57
Yes it is, not sure how many lightbox have you tried but I’ve been using them for years and all of them worked the same way by dragging.

Also this library is reaching almost 100k downloads and this is the only comment I’ve ever receive about this.

**Comment by biati-digital** [comment] 2020-07-04 17:04
I’m closing this as it’s not a bug, feel free to open a feature request but the scroll probably will not be implemented unless you have a really solid argument and examples.

**Comment by paxter** [comment] 2020-07-04 17:05
Ok I see. Your argument is if everybody does the same it have to be correct. For me it's a bug, because the expected behaviour on html content who is bigger than the screen, is to have the option to scroll down/right/left.

**Closed by biati-digital** 2020-07-04 17:04 UTC

**Comment by biati-digital** [comment] 2020-07-04 17:12
My argument is that if everyone does it certain way then people already know the functionality and how it works and use it. I’m not going to reinvent the wheel but again there’s always someone that it’s not happy and that’s ok you can always fork and do your own changes because this is not a bug.
