### ISSUE TITLE
Better httpr/ajax handling

### ISSUE THREAD

**Issue by loxK** [biati-digital/glightbox#231] opened 2021-04-27 01:23 UTC
Hello,

I am starting using glightbox to display forms. I followed the documentation en ended up with this:

```javascript
import GLightbox from 'glightbox/dist/js/glightbox';

export default () => {
    const lightbox = GLightbox( {selector: null, height: 'auto'} );

    document.querySelectorAll( '.inscription-reunion' ).forEach( button => {
        button.addEventListener( 'click', ( e ) => {
            e.preventDefault()
            wp.apiFetch( { path: '/vae/v1/briefing/publicSubscribeSelect' } ).then( response => {
                lightbox.setElements([])
                lightbox.insertSlide( {
                    content: response
                } );
                lightbox.open();
            } )
        } )
    })
}
``` 

The issue I have with this implementation is that there is a lag while it loads the content of the lightbox over httpr. What I would like is that the end-users get the lightbox loading indicator instantly and until the httpr content is loaded. I tried with the "open" event but it is not working as I intended it to.

I will also need to refresh the content. So, the behavior I am looking for, is: hide the lightbox's inner content, show the loading indicator, then the new content.

**Comment by frankie-tech** [comment] 2021-04-27 14:12
Hi @loxK,

Thank you for submitting this issue, a loading indicator for AJAX/fetch content is a nice enhancement/plugin candidate.

As for debugging the your issue, we don't offer debugging [support](https://github.com/biati-digital/glightbox#support). Your best bet for that would be [StackOverflow](https://stackoverflow.com/search).

**Comment by loxK** [comment] 2021-04-27 15:08
Hi,

The issue I have is related to Glightbox. Having to make the Ajax request before opening makes the apparent lag for users.

**Comment by frankie-tech** [comment] 2021-04-27 16:15
The lag you're descibing isn't a GLightbox issue. That issue depends on a users internet speed, the type of content being requested, the amount of content being requested, and the TTFB of the server that the request is being made to.

The GLightbox issue being described isn't that the AJAX request has to be made before opening the lightbox, the issue is that the lightbox can't be opened if there are no slides. This is by design.

There is nothing stopping you from creating your own solution.

For example, you can add your own loading overlay `onclick` and then remove it at the appropriate time using a GLightbox event, such as `open` or `slide_inserted`. What about a loading icon on the button being clicked?

These both sound like solutions for the problem you're describing. Still, this sounds like a feature request/plugin for v4, so I'll close this issue for now.

**Closed by frankie-tech** 2021-04-27 16:15 UTC
Labels: feature-request

**Comment by loxK** [comment] 2021-04-27 22:49
That's it, the design of the plugin doesn't properly work with Ajax.

**Comment by biati-digital** [comment] 2021-04-27 22:56
@loxK it never claimed it did, in the features at the top of the README is explained what the script can do. There are some examples of how you could implement it with Ajax but that's it, it's up to the developer to figure how to implement it or how to modify it to make it work the the way they need.

This could probably be implemented in V4.
