### ISSUE TITLE
Prevent Image from Being Panned Beyond Outer Edge (and out of the viewport)

### ISSUE THREAD

**Issue by kerns** [biati-digital/glightbox#105] opened 2020-04-19 21:18 UTC
**Describe the bug**
When zoomed on an image it seems possible to move/pan an image completely out of the viewport.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
Open an image that can be zoomed and move it to the edge of the viewport and keep going.

**Expected behavior**
An image should stop moving when you've hit the bounding area of the image...in other words, when moving it no longer reveals more image data, and only creates empty space.

**Screenshots**
<img width="1458" alt="Screen Shot 2020-04-19 at 23 16 02" src="https://user-images.githubusercontent.com/20254/79700137-02aec400-8294-11ea-82ce-6ac4d186e18c.png">

**Desktop:**
 - MacOS Catalina
 - Safari
 - Version 13.0.5 (15608.5.11)

**Comment by biati-digital** [comment] 2020-04-19 21:21
Duplicate of #61

**Closed by biati-digital** 2020-04-19 21:21 UTC
Labels: duplicate
