### ISSUE TITLE
Can not initilaze multiple galeries

### ISSUE THREAD

**Issue by flyingatm** [biati-digital/glightbox#262] opened 2021-07-06 00:31 UTC
**Describe the bug**

When there is an active glightbox, you are not able to open new glightbox above it. Spinner is stucking without any console error.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Open a lightbox that has a button which is triggers a new glightbox instance.
2. Click to that button.

**Expected behavior**

**Post the code you are using**

Well my code is very complicated but my description of the bug need to be enough to re-prod the bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/50561288/124526168-9ec9da00-de0a-11eb-821f-4e1a05d68102.png)

**Desktop:**
iOS, safari, chrome

**Comment by frankie-tech** [comment] 2021-07-07 11:46
Hey there @flyingatm,

I'm sorry but I'm not sure I understand what you're suggesting.

Are you trying to open a GLightbox from inside of another GLightbox? 

A code example would help me to understand the issue better.

**Comment by flyingatm** [comment] 2021-07-07 21:05
> Hey there @flyingatm,
> 
> I'm sorry but I'm not sure I understand what you're suggesting.
> 
> Are you trying to open a GLightbox from inside of another GLightbox?
> 
> A code example would help me to understand the issue better.

Hello sir, thank you for fast answer!

> Are you trying to open a GLightbox from inside of another GLightbox?

Yes.

But it's stucking with a loader spinner as I mentioned.

**Comment by frankie-tech** [comment] 2021-07-08 12:18
Not a sir, not a bug.

You're not supposed to be able to open multiple lightboxes inside of one another. For one thing it is an accessibility nightmare as well as an anti-pattern.

I'll leave this open as a feature request for now, but I recommend changing your approach or design to avoid nested modals/lightboxes.

**Comment by biati-digital** [comment] 2021-07-08 17:36
I agree with @frankie-tech, the library was not designed to have multiple instances open at the same time, i see a PR trying to add support for this but the changes are minimal, this will need much more work to ensure it works correctly with all kinds of events (keyboard, touch), devices, browser, etc. I do not recommend opening a lightbox inside a lightbox, it just does not feel right.

**Comment by frankie-tech** [comment] 2021-07-09 01:12
Yeah, I feel safe closing this. It's too much work, an anti-pattern, inaccessible, and outside of the scope of the library as @biati-digital said.

**Closed by frankie-tech** 2021-07-09 01:12 UTC
