### ISSUE TITLE
Call to "insertSlide" fails if lightbox has not been opened

### ISSUE THREAD

**Issue by sayontan** [biati-digital/glightbox#179] opened 2020-11-28 22:57 UTC
This is my test case: 

Let's say I have a gallery where I have 5 images. The gallery has an associated GLightbox instance, which has been set by initializing GLightbox with a selector. E.g.:

`lightbox = GLightbox({selector: '#gallery-1'});`

For the above I can click on an image and it shows up correctly in a lightbox. 

I also have a separate button, not related to GLightbox, that lets me add photos to the gallery. This is similar to the AJAX call you have listed in your example. The AJAX call returns a set of images that I insert at the end of the gallery, by calling `insertSlide` iteratively on them. Somthing like this:

```
lightbox.insertSlide({
    href: 'https://xxxxx', 
    title: 'abcd', 
    type: 'image'
});
```

Now, if I do the addition to the gallery after having previously opened the gallery, there is no issue. But, if I try to use `insertSlide` without first opening the lightbox, I get this error:

```
Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at GlightboxInit.insertSlide (glightbox.js:2635)
```

**Comment by biati-digital** [comment] 2020-11-29 11:45
Duplicate of #166

**Closed by biati-digital** 2020-11-29 11:45 UTC
